# Generated by Django 5.1.1 on 2024-09-12 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='title',
            new_name='reason',
        ),
    ]
