# Generated by Django 5.1.1 on 2024-09-13 05:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_project_name_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='from_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='note',
            name='to_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
