# Generated by Django 5.1.1 on 2024-09-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_note_from_date_note_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='from_date',
            field=models.DateField(default=models.DateField(auto_now_add=True)),
        ),
        migrations.AlterField(
            model_name='note',
            name='to_date',
            field=models.DateField(default=models.DateField(auto_now_add=True)),
        ),
    ]
