# Generated by Django 5.1.1 on 2024-09-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_notifications_message_notifications_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
