# Generated by Django 5.1.1 on 2024-09-26 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_task_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
    ]
