# Generated by Django 5.1.1 on 2024-10-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_profile_email_profile_firstname_profile_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hours_requested',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
