# Generated by Django 5.1.1 on 2024-10-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_task_hours_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hours_requested',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
