# Generated by Django 5.0.6 on 2024-07-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinghistory',
            name='Out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkinghistory',
            name='type',
            field=models.CharField(choices=[('fw', 'fw'), ('tw', 'tw')], max_length=10),
        ),
    ]
